# Generated by Django 5.2.6 on 2025-09-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
    ]
