# Generated by Django 5.2.6 on 2025-09-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_reminder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='presentation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
