# Generated by Django 5.2.6 on 2025-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_reminder_presentation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
